# Copyright (c) 2018, IBM
# Copyright 2012-2015 Docker, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Based on the opencontainers/runc .travis.yml file.

dist: xenial
language: go
go:
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

go_import_path: github.com/nabla-containers/runnc

sudo: required
services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libseccomp-dev genisoimage jq
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/vbatts/git-validation
  - go get -u github.com/golang/dep/cmd/dep
  - env | grep TRAVIS_

script:
  - git-validation -run DCO,short-subject -v
  - shellcheck tests/integration/run.bats
  - make build/runnc build/nabla-run
  - git submodule update --init --recursive
  - make build
  - make install
  - echo '{"runtimes":{"runnc":{"path":"/usr/local/bin/runnc"}}}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - make local-integration-test
