# Copyright (c) 2018, IBM
# Copyright 2012-2015 Docker, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Based on the opencontainers/runc .travis.yml file.

dist: xenial
language: go
go:
  - 1.11.x
  - tip

matrix:
  include:
    - go: "1.12"
      env: GO111MODULE=on
  allow_failures:
    - go: tip
    - env: GO111MODULE=on

go_import_path: github.com/nabla-containers/runnc

sudo: required
services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libseccomp-dev genisoimage jq
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/vbatts/git-validation
  - sh -c "if [ \"${GO111MODULE}\" != 'on' ]; then go get -u github.com/golang/dep/cmd/dep; fi"
  - env | grep TRAVIS_

script:
  - git-validation -run DCO,short-subject -v
  - make build/runnc build/nabla-run
  - git submodule update --init --recursive
  - make shellcheck
  - env GO111MODULE=on make build
  - env GO111MODULE=on make install
  - echo '{"runtimes":{"runnc":{"path":"/usr/local/bin/runnc"}}}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - make local-integration-test
